### PR TITLE
Add queens oolxd bundles and rename files for series

### PR DESCRIPTION
**Pull request by ryan-beisner**
Add xenial-queens and bionic-queens bundles, intended for all architectures

Use ceph-mon + ceph-osd instead of the deprecated ceph charm

Remove series from charm store urls

Rename bundles to include series name to support multiple series

### CODE REVIEW

**Comment by andrewdmcleod** [comment]
lgtm BUT since ceph doesnt currently work with s390x i think we need to either comment it out of the bundles, and/or comment to the effect and include bugs as to why it doesnt work

**Comment by sfeole** [comment]
why not just take ceph out completely on S390x?   and make a note,  "It does not work, and point them to a bug"

**Comment by ryan-beisner** [comment]
@sfeole @andrewdmcleod  But we CAN do ceph jewel (xenial distro), with openstack queens.  I just did that on arm64 due to a packaging delay.

In any case, I will rely on one of you to propose s390x bundle changes if/as needed.  Thank you.

**Comment by ryan-beisner** [comment]
Another note:  I'd prefer that s390x ceph issues be addressed as a separate review.

**Comment by sfeole** [comment]
Overall LGTM ok to merge, will create another PR for s390x related material

**Pull request merged**
