### PR TITLE
Migrate to openrc

### PR DESCRIPTION
**Pull request by fnordahl**

### CODE REVIEW

**Comment by sfeole** [comment]
LGTM , Once the docs on gerrit merge, +1 to merge this. 

https://review.openstack.org/#/c/557576/

**Review by ryan-beisner — CHANGES_REQUESTED** [review]
While I like the new openrc file, and the fact that it uses an rc file which is named the same as upstream docs, I would rather see a proposal for a decisive and complete change.

ie. just use the new openrc, and make novarc into a symlink, so that we just have one thing to maintain.

**Comment by ryan-beisner** [comment]
Also, there will need to be accompanying changes @ openstack/charm-guide.

**Comment by fnordahl** [comment]
Thx @ryan-beisner and done.

The first openrc iteration induced a change of behavior with how Keystone's IP was obtained, so that warranted a soft change. I have since changed it to obtain it in the same manner as the previous novarc, so it should be safe to do a clear cut.

Have already added a patch set with needed changes to charm-guide and I have also proposed changes to charm-deployment-guide.

Will follow up with PR to finish off the original novarc in openstack-bundles too.

**Pull request merged**
